# Generated by Django 2.2.5 on 2021-07-10 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashCards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_study', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='carddata',
            name='cards',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flashCards.Deck'),
            preserve_default=False,
        ),
    ]
